# Generated by Django 3.0.2 on 2021-04-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public circles are listed in the main page so everyone know about their existence.'),
        ),
    ]
