# Generated by Django 3.0.2 on 2021-04-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20210427_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public circles are listed in the main page so everyone knows about is existence.', verbose_name='public'),
        ),
    ]
